### ISSUE TITLE
cleanup the development org

### ISSUE THREAD

**Issue by arangari** [financialforcedev/df12-deployment-tools#17]
hi,

i am new to SF, and would like to understand if i can use the df12 dev tools to do the following:

1. cleanup the org - keeping only the installed packages. all the unmanaged code / customizations / custom tabs etc, should be removed.

2. deploy the changes.

FYI - i come from typical unix background with "make" way of deployment and expect that dev-org can be cleaned to restart the development.

**Comment by afawcett** [comment]
Firstly welcome to Salesforce! Deploy and building is a little different as i am sure your finding out. However your spot on in sticking to your principles on having a clean workspace or "org" as is the case here. So yes that is the aim of the undeploy, though i'm not sure if there is an issue if a managed / installed packaged exists, you'll have to try it and report back i think.
